verily-src/workbench-app-devcontainers

startupscript/vertex-ai-user-managed-notebook/post-startup.sh
the notebook config is a python file.
=> remove indentation

startupscript/vertex-ai-user-managed-notebook/post-startup.sh
relevant: https://github.com/verily-src/terra-service-ws-manager/pull/641
=> call terra resource update to set metadata

startupscript/dataproc/startup.sh, startupscript/post-startup.sh, startupscript/vertex-ai-user-managed-notebook/post-startup.sh
Changes similar to https://github.com/verily-src/terra-tool-cli/pull/342
=> Simplify script to fetch latest CLI version from Axon

startupscript/dataproc/startup.sh, startupscript/post-startup.sh, startupscript/vertex-ai-user-managed-notebook/post-startup.sh
Addressing https://github.com/verily-src/workbench-app-devcontainers/pull/28#discussion_r1396169901
=> [BENCH-1639] simplify error check in AFS call

startupscript/dataproc/startup.sh, startupscript/post-startup.sh, startupscript/vertex-ai-user-managed-notebook/post-startup.sh
Curl does not support --no-progress-bar during terra-cli installation, use alternate -s option
this addresses UI nightly errors
=> Use alternate option for curl

startupscript/post-startup.sh
the rest of the script uses RUN_AS_LOGIN_USER
this will prevent accidental copy and paste error
=> Update post-startup.sh to use RUN_AS_LOGIN_USER

startupscript/dataproc/startup.sh, startupscript/post-startup.sh, startupscript/vertex-ai-user-managed-notebook/post-startup.sh
Required as part of https://github.com/verily-src/terra-tool-cli/pull/355
=> [BENCH-1744] Update ssh-key command

startupscript/dataproc/startup.sh, startupscript/post-startup.sh, startupscript/vertex-ai-user-managed-notebook/post-startup.sh
Issue: the terra installation runs as login user, and mv terra installation is not needed to be run as that user
fix: split it
fix identified and provided by @yuhuyoyo
=> Dexamundsen patch 1

template/.devcontainer.json, template/README.md, template/docker-compose.yaml
as i'm writing the howto doc for creating apps, template seems useful.
=> add a template for app devcontainer

jupyter/.devcontainer.json, rstudio/.devcontainer.json, startupscript/bash-completion.sh, startupscript/emit.sh, startupscript/git-setup.sh, startupscript/install-java.sh, startupscript/post-startup.sh, vscode/.devcontainer.json
https://verily.atlassian.net/browse/BENCH-1933
install java as a devcontainer feature.
next step is to pull out gcp specific part into a gcp folder.
=> BENCH-1933: modularize part of the post-startup.sh

startupscript/install-java.sh, startupscript/post-startup.sh
I renamed the variable in the main script but forgot about the subscript. To prevent this from happening, I'm passing the user name as param into the subscript.
=> Fix the startup script

.github/workflows/test-pr.yaml, src/idlechecker/.devcontainer.json, src/idlechecker/devcontainer-template.json, src/idlechecker/idle-checker.sh
https://verily.atlassian.net/browse/BENCH-2520
=> new devcontainer for idle checking

startupscript/vertex-ai-user-managed-notebook/post-startup.sh
only run the custom proxy agent when the user has non-google-account=true
https://verily.atlassian.net/browse/BENCH-2608
=> check whether the user has a google account

startupscript/butane/004-git-clone-devcontainer.sh, startupscript/butane/006-start-proxy-agent.sh, startupscript/butane/probe-user-access.sh, startupscript/dataproc/startup.sh
```
set -o errexit
set -o nounset
set -o pipefail
set -o xtrace 
```
makes the script more robust but also catches issues like pipe failure.
https://verily.atlassian.net/browse/BENCH-2603
=> Fix butane scripts

startupscript/butane/aws/metadata-utils.sh
should not echo logs in get_metadata_value
=> fix aws metadata util script

startupscript/butane/idle-shutdown.sh
it's also consistent with vertex ai guest attributes
=> set notebooks/last-activity for the UI

src/cirrocumulus/.devcontainer.json, src/jupyter/.devcontainer.json, src/rstudio/.devcontainer.json, src/shiny/.devcontainer.json, src/vscode/.devcontainer.json, startupscript/aws/configure-aws-vault.sh, startupscript/remount-on-restart.sh
One more change that escaped my initial testing.  I tested this with custom apps for each of the touched devcontainer configs and it remounts successfully.
=> Fix remounting on restart to work in both clouds.

startupscript/butane/metadata-cleanup.sh, startupscript/butane/probe-user-access.sh
this needs to go in first.
then i change verily1 to use it. 
then i update the deployment to use this in the downstream app-manger repo.
=> add a script for cleaning up metadata

startupscript/aws/vm-metadata.sh, startupscript/butane/devcontainer-failure-handler.sh, startupscript/butane/pre-devcontainer.sh, startupscript/butane/probe-proxy-readiness.sh, startupscript/gcp/vm-metadata.sh, startupscript/post-startup.sh
Copy over error logging from Vertex AI post startup script to the custom app post startup script.
=> BENCH-3240: Add exit and error logging to post startup script when importing custom application

.github/workflows/release.yaml
=> Only run this workflow when manually triggered

startupscript/dataproc/startup.sh, startupscript/vertex-ai-user-managed-notebook/post-startup.sh
https://verily.atlassian.net/browse/BENCH-4344
=> Update java download path

startupscript/dataproc/startup.sh
We were only conditionally setting APP_PROXY
=> fix unbounded variable

startupscript/gcp/post-startup-hook.sh, startupscript/gcp/vm-metadata.sh, startupscript/post-startup.sh, test/vm-metadata.sh
The Mikey custom app has a BQ/GCS Jupyterlab plugin that depends on this config being set.
=> BENCH-4825: Set instance region gcloud config on post startup

startupscript/aws/vm-metadata.sh, startupscript/setup-bashrc.sh
Adds `--region` to `aws ec2` commands.
=> AWS CLI EC2 commands require region.

startupscript/butane/006-start-proxy-agent.sh
More detail context in this corresponding PR: https://github.com/verily-src/verily1/pull/52616
[BENCH-5371](https://verily.atlassian.net/browse/BENCH-5371)
[BENCH-5371]: https://verily.atlassian.net/browse/BENCH-5371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BENCH-5371] Add config to enable monitoring script in proxy-agent

.github/workflows/test-pr.yaml, src/jupyter-aou/.devcontainer.json, src/jupyter-aou/README.md, src/jupyter-aou/devcontainer-template.json, src/jupyter-aou/docker-compose.yaml
Adds a devcontainer template for the AoU Jupyter app
BENCH-5437
=> AoU Jupyter App

startupscript/dataproc/startup.sh
=> [BENCH-5473] Modify banner for vwb proxy

startupscript/dataproc/startup.sh
Ensure that the VWB proxy agent startup script can be safely rerun without causing errors or redundant insertions. This should be effective during system reboots or when restarting after a failure.
BENCH-5473
=> [BENCH-5473] Make proxy agent service startup idempotent

startupscript/butane/006-start-proxy-agent.sh
=> set log max size and file

startupscript/dataproc/startup.sh
=> add log caps for data proc cluster app proxy agent

startupscript/butane/006-start-proxy-agent.sh, startupscript/dataproc/startup.sh
=> [BENCH-5431] Enable websocket tunnel based on VM metadata

startupscript/butane/devcontainer-failure-handler.sh
=> Add shutdown option with devcontainer failure handler

src/libreoffice/docker-compose.yaml, src/shiny/Dockerfile, src/shiny/docker-compose.yaml, src/vscode/docker-compose.yaml
New versions with old caches cause cache misses
=> Pin app versions

startupscript/butane/006-start-proxy-agent.sh, startupscript/dataproc/startup.sh
Otherwise it would use the cached version
=> Pull proxy agent image before starting

startupscript/butane/005-parse-devcontainer.sh
1. devcontainer.json can either lives in .devcontainer/devcontainer.json or just .devcontainerjson in the root project. Currently it only handles the latter.
2. there may not be a docker-compose.yaml file.
PHP-74142
=> fix the script for devcontainer parser

.github/actions/smoke-test/build.sh, features/src/workbench-tools/README.md, features/src/workbench-tools/devcontainer-feature.json, features/src/workbench-tools/install.sh, src/custom-workbench-jupyter-template/.devcontainer.json, src/jupyter-aou/.devcontainer.json, src/jupyter-template/.devcontainer/features, src/libreoffice/.devcontainer/features, src/r-analysis/.devcontainer.json, src/vscode/.devcontainer.json, startupscript/butane/005-parse-devcontainer.sh, startupscript/post-startup.sh
A few of these are built from source since there is no binary available via the system package manager (i.e. apt-get). conda includes most of them, but our JupyterLab app is the only one with conda. Thus, this could take ~20 mins to build, so we should only really use them with cached apps
PHP-71105
=> Add bioinformatics tools to new workbench-tools devcontainer feature

README.md, startupscript/butane/004-git-clone-devcontainer.sh
Git switch was running in the wrong directory
=> Fix git switch command

startupscript/butane/004-git-clone-devcontainer.sh
fix error fatal: '--detach' cannot be used with '-b/-B/--orphan'
=> attach origin/ to the branch if it's a remote branch

src/custom-workbench-jupyter-template/.devcontainer/features, src/jupyter-aou/.devcontainer/features, src/jupyter-template/.devcontainer/features, src/libreoffice/.devcontainer/features, src/r-analysis/.devcontainer/features, src/vscode/.devcontainer/features, startupscript/butane/001-install-node.sh, startupscript/butane/005-parse-devcontainer.sh, startupscript/butane/devcontainer.sh, startupscript/butane/prepare-devcontainer-cache.sh
=> Clean up devcontainer symlinks and /opt/bin

feature-versions/state.json, src/aou-common/extension-builder/Dockerfile, src/jupyter-aou/Dockerfile, src/jupyter-aou/docker-compose.yaml, src/nemo_jupyter_aou/docker-compose.yaml, src/workbench-jupyter-parabricks-aou/docker-compose.yaml
Reverts verily-src/workbench-app-devcontainers#241
Failed to build cache with new aou image, will investigate more Monday
=> Revert "Automated devcontainer feature update"
