- startupscript/vertex-ai-user-managed-notebook/post-startup.sh
https://verily.atlassian.net/browse/BENCH-1515
on reboot, the `rc-local.service` will overwrite proxy.env again because `attempt-register-vm-on-proxy.sh` is added to /etc/rc.local. [attempt-register-vm-on-proxy.sh](https://source.corp.google.com/piper///depot/google3/cloud/ml/dset/dlenv/build/vm/packer/clean/files/c2d/scripts/01-attempt-register-vm-on-proxy.sh;l=24)
> BENCH-1515: start workbench app proxy agent as a separete systemd unit

- startupscript/vertex-ai-user-managed-notebook/post-startup.sh
Support an additional user supplied startup script.
Reopened from https://github.com/DataBiosphere/terra-workspace-manager/pull/1503 and addressed the comments there.
Ticket: https://verily.atlassian.net/browse/BENCH-1371
> BENCH-1371: Add support for user provided startup script for vertex AI notebooks

- startupscript/dataproc/startup.sh
- startupscript/post-startup.sh
- startupscript/vertex-ai-user-managed-notebook/post-startup.sh
RC - variable exit_code was being set only in the context of the previous statement, and hence not accessible in the subsequent if block
fix - init the exist_status variable in a new line so that it is accessible in rest of code flow
> [BENCH-1639] Separate exit_status init from previous command

- startupscript/dataproc/startup.sh
Inject a workspace link in the dataproc component proxy banner. 
Ticket: https://verily.atlassian.net/browse/BENCH-1233
> BENCH-1233: Append workspace link in proxy agent banner

- startupscript/dataproc/install-r.sh
Adds an initialization action to install the latest version of R on all dataproc cluster nodes. See https://verily.atlassian.net/browse/BENCH-1769 for more details.
For the short term, we need to put this script in our public gcs bucket as initialization scripts only supports public gcs files, so we can't use a github file url.
Followup work: Modify WSM to pass this script as an initialization action on cluster creation.
> BENCH-1769: Install latest version of R in dataproc startup script

- .github/actions/smoke-test/build.sh
- .github/actions/smoke-test/test.sh
- .github/workflows/test-pr.yaml
- startupscript/README.md
- startupscript/dataproc/install-r.sh
- startupscript/dataproc/startup.sh
- startupscript/gcp/resource-mount.sh
- startupscript/git-setup.sh
- startupscript/install-cli.sh
- startupscript/post-startup.sh
- startupscript/setup-bashrc.sh
- startupscript/vertex-ai-user-managed-notebook/post-startup.sh
- test/test-utils/test-utils.sh
- test/test.sh
Enables PR check to lint shell scripts with `shellcheck`.  Script changes are needed to get a clean linter run.
These changes have been tested with AI Notebook, Dataproc Cluster, and custom apps.
> Add shellcheck step to PR workflow.

- src/cirrocumulus/scripts/cirro_scanner.sh
jq: error: syntax error, unexpected '{', expecting IDENT or __loc__ (Unix shell quoting issues?) at <top-level>, line 1: .[] | select(.url == ${path})                       jq: 1 compile error
> fix jq syntax error

- src/cirrocumulus/.devcontainer.json
- src/jupyter/.devcontainer.json
- src/rstudio/.devcontainer.json
- src/shiny/.devcontainer.json
- src/vscode/.devcontainer.json
I'm not sure what the intent of our vscode app is, but these changes are necessary to be able to build Workbench Java code in the app (lock to Java 17, `gcloud`needed for private artifacts), which I have found very useful for testing in-EC2 behavior.
> Enable Building Workbench Java Code in VS Code

- startupscript/dataproc/startup.sh
- startupscript/vertex-ai-user-managed-notebook/post-startup.sh
This change allows users to toggle whether hidden files (prefixed with `.`) are shown in the Jupyter file browser or not. By enabling this setting, Jupyter adds a "Show hidden files" option under the `View` menu. By default this is off, which matches previous behavior.
I've added this for all notebooks and dataproc clusters (including ones via custom image) as this option was [added in Jupyterlab 3.2.0](https://github.com/jupyterlab/jupyterlab/issues/2049)(early 2022). My assumption is that users are not using significantly older versions of Jupyterlab - please let me know if that's not true and I can avoid setting it for custom images.
> [BENCH-855] Allow users to toggle display of hidden files in jupyter browser

- startupscript/aws/bashrc-functions.bash
- startupscript/aws/post-startup-hook.sh
- startupscript/aws/vm-metadata.sh
Makes the following changes:
- Fixes wrong tag prefix in AWS startup script `get_metadata_value` function (`s/vwbapp/vwbuser`).
- Uses `WorkspaceId` tag for "no-login" path, as this will always be present, and always be set to the Workspace UUID.  Renamed variables `s/WORKBENCH_WORKSPACE/WORKBENCH_WORKSPACE_UUID` to make this explicit.
Note that the "no-login" paths will be removed once the AWS AuthNZ is released to all environments.  So this is a workaround to prevent having to phase in the WSM fix to use user-facing ID for the `vwbusr:terra-workspace-id` tag.
> AWS Startup Script Fixes

- startupscript/aws/configure-aws-vault.sh
- startupscript/aws/post-startup-hook.sh
- startupscript/aws/resource-mount.sh
- startupscript/git-setup.sh
- startupscript/install-cli.sh
- startupscript/setup-bashrc.sh
Enables non-interactive configuration in AWS on par with GCP when no-cred AWS authentication is enabled in the environment.
Key changes:
- Breaks out `aws-vault` config into separate script for reuse.
- Skip all of the extra config steps required when AWS login is enabled (we will be able to remove a bunch of code once AWS no-cred authn has propagated to all envs).
- Use direct call to git instead of `wb git clone --all`.  The CLI "passthrough" commands have a fundamental assumption that Google App Default Creds are configured, which only holds in GCP VM's.  This is pretty baked into the CLI's "external command" design, even though `git` doesn't use ADC, and would require some significant refactoring in CLI to change.  Scripting the same behavior is cloud-agnostic and trivial, so did that …
> Enable non-interactive login path for AWS.

- startupscript/butane/004-git-clone-devcontainer.sh
Because we modify the template after cloning, devcontainer.service fails on reboot when trying to pull.
> Skip cloning if repo is already cloned

- startupscript/butane/005-parse-devcontainer.sh
- Script needs to find node in the path.
- Hardcoded config path.
> Fix two bugs in devcontainer parse

- src/libreoffice/.devcontainer.json
- src/libreoffice/docker-compose.yaml
- startupscript/aws/resource-mount.sh
- startupscript/gcp/resource-mount.sh
- startupscript/git-setup.sh
- startupscript/post-startup.sh
Changes include (mainly for alpine Linux):
- Using APK package manager instead of APT.
- Installing gcsfuse from source as it is not available for APK.
> Enable CLI installation on libreoffice

- startupscript/butane/005-parse-devcontainer.sh
- startupscript/butane/aws/metadata-utils.sh
- Quotes and backslashes need to be escaped
- Also make the json we write more compact as there is a size limit
> Fix setting metadata on aws that contains special cars

- src/rstudio/docker-compose.yaml
I tested this via a fork and it (superficially) seemed to be fine.
I tested in devel.
> update rstudio image to bump version to 4.4

- startupscript/aws/vm-metadata.sh
Docker command not available in container. Use aws cli command directly.
> BENCH-3240: Fix set_metadata for AWS

- startupscript/install-cli.sh
The install cli script defines `TERRA_SERVER` inside the check for whether the cli is installed, so retries will fail later in the script with unbound var error. This PR moves it out of the check so that the actual failure is retried.
> Fix install CLI retry

- startupscript/butane/005-parse-devcontainer.sh
- startupscript/butane/nvidia-runtime.yaml
This change modifies the `parse-devcontainer.sh` script to accept an accelerator param to conditionally insert a gpu runtime block in the docker compose file of the devcontainer. This block tells docker to reserve nvidia GPU devices in the VM.
The script is rewritten to be idempotent so that on reruns (in the future), we can determine whether the gpu reservation block should be set or not set depending if the VM has a gpu attached. This to get us one step closer to making gpu editability work with Mikey apps.
> BENCH-4629: Conditionally insert nvidia runtime block in docker-compose

- startupscript/post-startup.sh
The startupscript adds a code snippet to bashrc that modifies the path variable. However the startup script does not escape $, resulting in the PATH var expanding into the value of the PATH var at the execution time of the startup script. This is breaking anyone from adding paths to PATH.
> Prevent unintended variable expansion in modifying the path var in the bashrc code snippet

- startupscript/butane/attach-docker-cache.sh
- startupscript/butane/prepare-devcontainer-cache.sh
`prepare-devcontainer-cache.sh` prepares the devcontainer to be saved as a disk image
`attach-docker-cache.sh` scans for any newly attached docker cache disks and mounts them and integrates them with the docker root directory.
BENCH-5651
> Add docker cache scripts

- startupscript/dataproc/startup.sh
Corresponding PR: [add config flag for dataproc startup script](https://github.com/verily-src/terra-service-ws-manager/pull/1093)
BENCH-5473
[BENCH-5473]: https://verily.atlassian.net/browse/BENCH-5473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BENCH-5473] Switching Dataproc to Use Workbench Proxy

- src/workbench-jupyter-docker/.devcontainer.json
- src/workbench-jupyter-docker/README.md
- src/workbench-jupyter-docker/devcontainer-template.json
- src/workbench-jupyter-docker/docker-compose.yaml
- startupscript/setup-docker.sh
Supports Docker out of Docker (DooD) by exposing the docker socket and running jupyter under the docker group.
Mostly #149 with some small changes from #163
> create workbench-jupyter-docker devcontainer to support docker workflows

- startupscript/dataproc/startup.sh
https://docs.docker.com/engine/logging/drivers/gcplogs/
> Dataproc's default logging driver is google cloud logging

- src/jupyter-aou/.devcontainer.json
- src/jupyter-aou/build/Dockerfile
- src/jupyter-aou/build/remotefuse/fusermount
- src/jupyter-aou/build/remotefuse/gcsfuse
- src/jupyter-aou/build/remotefuse/goofys
- src/jupyter-aou/build/remotefuse/remotefuse
- src/jupyter-aou/docker-compose.yaml
- src/jupyter-aou/remotefuse/Dockerfile
- src/jupyter-aou/remotefuse/entrypoint.sh
- src/jupyter-aou/remotefuse/remotefuse
- src/jupyter-aou/startup.sh
This forwards gcsfuse, goofys, and fusermount commands via ssh to the remotefuse sidecar, which operates on a mount shared with the main container. With this, the main container does not need CAP_SYS_ADMIN
PHP-70786
> Move fuse commands to a sidecar for jupyter-aou

- startupscript/butane/004-git-clone-devcontainer.sh
`git clone -b` only supports branch names, we also want to be able to select a commit hash
> Allow creating devcontainer off of specific commit hash

- src/jupyter-aou/remotefuse/Dockerfile
gcsfuse isn't available for Debian 13 yet
> Pin remotefuse to Debian 12

- startupscript/butane/aws/credential-helper.sh
Fix docker credentials helper script, which fails when called by the docker daemon since it aggressively closes the pipe to stdin, causing the `read` bash buitin to return non-zero despite receiving all input data.
> Fix docker credentials helper script.

- features/src/workbench-tools/NOTES.md
- features/src/workbench-tools/README.md
- features/src/workbench-tools/devcontainer-feature.json
- features/src/workbench-tools/install.sh
- src/custom-workbench-jupyter-template/.devcontainer.json
- src/jupyter-aou/.devcontainer.json
- src/r-analysis/.devcontainer.json
- src/vscode/.devcontainer.json
Adds a new cloud parameter to specify the cloud the app is running on. If the cloud is "gcp", installFromSource will default to true for workbench-tools.
PHP-71105
> Enable installFromSource for workbench-tools feature in GCP apps

- startupscript/remount-on-restart.sh
remount-on-restart assumes WORKBENCH_INSTALL_PATH is set which is not true when the container is restarting after a prior create
> Set WORKBENCH_INSTALL_PATH when remounting after container restart
